export enum RegisterEnum {
	CONFIRMATION_EMAIL = "CONFIRMATION_EMAIL",
	TOKEN_REQUIRED = "TOKEN_REQUIRED",
	INVALID_PIN = "INVALID_PIN",
	TOKEN_EXPIRED = "TOKEN_EXPIRED",
	RESET_PASSWORD = "RESET_PASSWORD",
	VALID_PIN = "VALID_PIN",
	FORGOT_PASSWORD = "FORGOT_PASSWORD",
	VERIFIED_ACCOUNT = "VERIFIED_ACCOUNT",
}